### ISSUE TITLE
I think ribbon  is not used in this project

### ISSUE THREAD

**Issue by conanca** [yidongnan/spring-cloud-consul-example#3]
but with this dependencies : compile('org.springframework.cloud:spring-cloud-starter-ribbon')

**Comment by yidongnan** [comment]
@conanca Spring Cloud integrates Ribbon to provide a load balanced http client when using Feign.

**Comment by conanca** [comment]
明白了
刚注意到spring-cloud-starter-ribbon 是被spring-cloud-starter-feign依赖的
所以我觉得你完全可以不用显式的配置这个依赖
