### ISSUE TITLE
怎么解决服务向consul注册的时候，ip地址的问题

### ISSUE THREAD

**Issue by yangBin666** [yidongnan/spring-cloud-consul-example#5]
怎么解决服务向consul注册的时候，ip地址的问题？
然后这行配置spring.profiles.active=docker是什么意思？是指对应一个docker的配置文件吗？

**Comment by yidongnan** [comment]
@yangBin666 什么ip地址的问题？
下面的配置可以自行查阅spring profile的相关资料

**Comment by yangBin666** [comment]
配置的问题已经理解，ip地址在同一个docekr环境下可以访问
